
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
      - DATABASE_URL=mysql://root:root@db:3306/issue_tracker
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    depends_on:
      - db
    command: sh -c "
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npm run build --verbose &&
      npm start"

  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issue_tracker
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: